name: Email action
on: [push]  
jobs:  
  send-email:  
    runs-on: ubuntu-latest  
    steps:
      - name: send mail  
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
        subject: Email sent via Github actions
        to: pranjalmishra2022@gmail.com,bunumishu@gmail.com
        from: Github action bot
        secure: true
        body: Email sent by actions !!!
        

