name: Execute script  
on: [push]  
jobs:  
  exec-script:
    runs-on: ubuntu-latest  
    steps:  
      - uses: actions/checkout@v2
      - run: |
          chmod +x script.sh
          ./script.sh
        shell: bash 