name: Schedule Event every 5 mins
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  test-schedule:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job has run at scheduled time. Next run will be after 5 mins"